version: '3.9'
services:
  postgres:
    container_name: kotlin-service-postgres
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kotlinservice
    volumes:
      - postgres-kotlin-service:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-kotlin-service:
